name = "Torch"
uuid = "6a2ea274-3061-11ea-0d63-ff850051a295"
authors = ["dhairyagandhi96 "]
version = "0.1.2"

[deps]
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Torch_jll = "c12fb04c-f5e9-5c82-b5d6-b53f8f8d9a32"
ZygoteRules = "700de1a5-db45-46bc-99cf-38207098b444"

[compat]
FillArrays = "0.8"
NNlib = "0.6, 0.7"
Requires = "1"
ZygoteRules = "0"
julia = "1.3"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Metalhead = "dbeba491-748d-5e0e-a39e-b530a07fa0cc"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Flux", "Metalhead", "Documenter", "IterTools", "LinearAlgebra"]
